default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 3aKKctun

development:
  <<: *default
  database: sprinkles_development

test:
  <<: *default
  database: sprinkles_test

production:
  <<: *default
  database: sprinkles_production
