default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sprinkles_development

test:
  <<: *default
  database: sprinkles_test

production:
  <<: *default
  database: sprinkles_production
